apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: kistek-consulting
  labels:
    k8s-app: kistek-consulting
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: kistek-consulting
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: metrics
    scheme: http
    interval: 30s
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
